/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otb;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MediaTracker;
import javafx.scene.layout.BackgroundImage;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Shubhashis
 */
public class LogInRegister extends javax.swing.JFrame{
    Border raiseBorder,emptyBorder;
    /**
     * Creates new form LogInRegister
     */
    public LogInRegister() {
        initComponents();
        adminRadioButton.setSelected(true);
        regAdminRad.setSelected(true);
        setLocationRelativeTo(this);
        raiseBorder = BorderFactory.createEtchedBorder(Color.WHITE, Color.WHITE);
        emptyBorder = BorderFactory.createEmptyBorder();
        jButton2.setBorder(raiseBorder);
        
//        add(new contentPanel());
        //setSize(500,300);
//        background gui = new background();
//        JLabel gh = new JLabel(new ImageIcon(this.getClass().getResource("/otb/back.jpg")));
//        gh.setOpaque(true);
//        gh.setLayout(new BorderLayout());
//        System.err.println("asce");
//        gui.setContentPane(gh);
//        
//        System.err.println("3242");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        signIn = new javax.swing.JPanel();
        logInPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        logInUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        forgotPasswordButton = new javax.swing.JButton();
        adminRadioButton = new javax.swing.JRadioButton();
        clientRadioButton = new javax.swing.JRadioButton();
        newUser = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        regEmailText = new javax.swing.JTextField();
        regAdminRad = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        regPhoneText = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        regUserText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        regRePassText = new javax.swing.JPasswordField();
        regPassText = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        regNameText = new javax.swing.JTextField();
        regClientRad = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Ticket Booking");
        setIconImage(Toolkit.getDefaultToolkit().getImage(JFrame.class.getResource("/otb/seat/icon.jpg")));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 21, 21));

        jButton2.setBackground(new java.awt.Color(21, 21, 21));
        jButton2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign In");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(21, 21, 21));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NEW USER ?");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.CardLayout());

        signIn.setBackground(new java.awt.Color(69, 63, 72));
        signIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        signIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logInPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logInPassword.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UserName");

        logInUser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logInUser.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");

        jButton11.setBackground(new java.awt.Color(69, 63, 72));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otb/seat/login.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        forgotPasswordButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        forgotPasswordButton.setForeground(new java.awt.Color(102, 153, 255));
        forgotPasswordButton.setText("Forgot Password");
        forgotPasswordButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        forgotPasswordButton.setBorderPainted(false);
        forgotPasswordButton.setContentAreaFilled(false);
        forgotPasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordButtonActionPerformed(evt);
            }
        });

        adminRadioButton.setBackground(new java.awt.Color(69, 63, 72));
        buttonGroup1.add(adminRadioButton);
        adminRadioButton.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        adminRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        adminRadioButton.setText("Admin");

        clientRadioButton.setBackground(new java.awt.Color(69, 63, 72));
        buttonGroup1.add(clientRadioButton);
        clientRadioButton.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        clientRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        clientRadioButton.setText("Client");
        clientRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signInLayout = new javax.swing.GroupLayout(signIn);
        signIn.setLayout(signInLayout);
        signInLayout.setHorizontalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInLayout.createSequentialGroup()
                .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(logInUser, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(logInPassword)))
                    .addGroup(signInLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel8))
                    .addGroup(signInLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel9))
                    .addGroup(signInLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(signInLayout.createSequentialGroup()
                                .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(signInLayout.createSequentialGroup()
                                        .addComponent(clientRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17))
                            .addGroup(signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(forgotPasswordButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signInLayout.setVerticalGroup(
            signInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forgotPasswordButton)
                .addGap(18, 18, 18)
                .addComponent(adminRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(signIn, "card2");

        newUser.setBackground(new java.awt.Color(69, 63, 72));
        newUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");

        regEmailText.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        regAdminRad.setBackground(new java.awt.Color(69, 63, 72));
        buttonGroup2.add(regAdminRad);
        regAdminRad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        regAdminRad.setForeground(new java.awt.Color(255, 255, 255));
        regAdminRad.setText("Admin");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Retype Password");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");

        regPhoneText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButton9.setBackground(new java.awt.Color(69, 63, 72));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otb/register.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");

        regUserText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Username");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Phone no");

        regNameText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        regClientRad.setBackground(new java.awt.Color(69, 63, 72));
        buttonGroup2.add(regClientRad);
        regClientRad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        regClientRad.setForeground(new java.awt.Color(255, 255, 255));
        regClientRad.setText("Client");

        javax.swing.GroupLayout newUserLayout = new javax.swing.GroupLayout(newUser);
        newUser.setLayout(newUserLayout);
        newUserLayout.setHorizontalGroup(
            newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserLayout.createSequentialGroup()
                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel11))
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(newUserLayout.createSequentialGroup()
                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regRePassText, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(newUserLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserLayout.createSequentialGroup()
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(regAdminRad)
                                    .addComponent(regClientRad))
                                .addGap(133, 133, 133)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel14))
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel12))
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel7)))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        newUserLayout.setVerticalGroup(
            newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(regEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regRePassText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserLayout.createSequentialGroup()
                        .addComponent(regAdminRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regClientRad))
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(newUser, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setBorder(raiseBorder);
        jButton1.setBorder(emptyBorder);
        
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(signIn);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String usernameString=logInUser.getText();
        String passwordString=logInPassword.getText();
        Integer type = 1;
        if(adminRadioButton.isSelected()==true) type =1;
        else if(clientRadioButton.isSelected()==true) type =2;

        if(usernameString.length()==0 || passwordString.length()==0 || type==0)
        {
            JOptionPane.showMessageDialog(this, "Correct the Input .","WRONG ENTRY !!",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            String sql = "Select * from users where type like '"+type+"' and username like '"+usernameString+"' and password like '"+passwordString+"'";
            if(DatabaseHelper.find(sql)==true)
            {
                if(type==2)
                {
                    MainFrame ob = new MainFrame();
                    ob.setVisible(true);
                    ob.setUserNameFromLogIn(usernameString);
                    this.setVisible(false);
                }
                else
                {
                    AdminPanel ob = new AdminPanel();
                    ob.setVisible(true);
                    this.setVisible(false);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid Credentials","WRONG ENTRY",JOptionPane.INFORMATION_MESSAGE);
                logInPassword.setText("");
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void forgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordButtonActionPerformed
        // TODO add your handling code here:
        ResetUser ob = new ResetUser();
        ob.setVisible(true);
    }//GEN-LAST:event_forgotPasswordButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setBorder(raiseBorder);
        jButton2.setBorder(emptyBorder);
        
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(newUser);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String name="", email="", phoneNo="", username="", password="", rePassword="";
        Integer type=1;
        try 
        {
            name = regNameText.getText();
            email = regEmailText.getText();
            phoneNo = regPhoneText.getText();
            username = regUserText.getText();
            password = regPassText.getText();
            rePassword = regRePassText.getText();

        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(this,"Fill up all box", "Wrong Entry !!",JOptionPane.INFORMATION_MESSAGE);
        }

        if(regAdminRad.isSelected()==true) type=1;
        else if(regClientRad.isSelected()==true) type =2;

        if(regAdminRad.isSelected()==false && regClientRad.isSelected()==false)
        {
            JOptionPane.showMessageDialog(this, "Select Admin or Client !!","WARNING !!",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(password.equals(rePassword)==false)
        {
            JOptionPane.showMessageDialog(this, "Password Mismatch !!","WARNING !!",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(name.length()==0 || email.length()==0 || phoneNo.length()==0 || username.length()==0 || password.length()==0 || rePassword.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Fill up all box","Wrong Entry !!",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            String sql = "Select * from users where username like '"+username+"'";
            if(DatabaseHelper.find(sql)==true)
            {
                JOptionPane.showMessageDialog(this, "Same ID exists!!","WARNING !!",JOptionPane.INFORMATION_MESSAGE);
                regUserText.setText("");
                regPassText.setText("");
                regRePassText.setText("");
            }
            else
            {
                sql = "Insert into users values (null,'"+type+"','"+name+"','"+email+"','"+phoneNo+"','"+username+"','"+password+"')";
                //sql = "Insert into users valuse (null,sd,sd,21,sd,123)";
                if(DatabaseHelper.insert(sql)==true)
                {
                    JOptionPane.showMessageDialog(this, "You Are Registered !!", "Registration", JOptionPane.INFORMATION_MESSAGE);
                    regNameText.setText("");
                    regEmailText.setText("");
                    regPhoneText.setText("");
                    regUserText.setText("");
                    regPassText.setText("");
                    regRePassText.setText("");
                    LogInRegister ob = new LogInRegister();
                    ob.setVisible(true);
                    this.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Check Your Connection", "Try Again", JOptionPane.INFORMATION_MESSAGE);
                    regPassText.setText("");
                    regRePassText.setText("");
                }
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void clientRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LogInRegister().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton clientRadioButton;
    private javax.swing.JButton forgotPasswordButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField logInPassword;
    private javax.swing.JTextField logInUser;
    private javax.swing.JPanel newUser;
    private javax.swing.JRadioButton regAdminRad;
    private javax.swing.JRadioButton regClientRad;
    private javax.swing.JTextField regEmailText;
    private javax.swing.JTextField regNameText;
    private javax.swing.JPasswordField regPassText;
    private javax.swing.JTextField regPhoneText;
    private javax.swing.JPasswordField regRePassText;
    private javax.swing.JTextField regUserText;
    private javax.swing.JPanel signIn;
    // End of variables declaration//GEN-END:variables


}
//
//class contentPanel extends JPanel{
//    Image img = null;
//
//    public contentPanel() {
//        MediaTracker mt = new MediaTracker(this);
//        img = Toolkit.getDefaultToolkit().getImage("/otb/back.jpg");
//        mt.addImage(img, 0);
//        try {
//            mt.waitForAll();
//        } catch (InterruptedException ex) {
//            Logger.getLogger(contentPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//
//    @Override
//    protected void paintComponent(Graphics g) {
//        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
//        int h = img.getHeight(null);
//        int w = img.getWidth(null);
//
//        // Scale Horizontally:
//        if ( w > this.getWidth() )
//        {
//            img = img.getScaledInstance( getWidth(), -1, Image.SCALE_DEFAULT );
//            h = img.getHeight(null);
//        }
//
//        // Scale Vertically:
//        if ( h > this.getHeight() )
//        {
//            img = img.getScaledInstance( -1, getHeight(), Image.SCALE_DEFAULT );
//        }
//
//        // Center Images
//        int x = (getWidth() - img.getWidth(null)) / 2;
//        int y = (getHeight() - img.getHeight(null)) / 2;
//
//        // Draw it
//        g.drawImage( img, x, y, null );
//    }
//    
//    
//    
//}